# Generated by Django 3.1 on 2020-09-01 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo:')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion del cargo:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, verbose_name='Color:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cedula:')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre del empleado:')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido del empledado:')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion del empleado:')),
                ('telefonos', models.CharField(max_length=80, verbose_name='telefonos del empleado:')),
                ('email', models.CharField(max_length=30, verbose_name='Correo Electronico:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.cargos')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Fincas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre:')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion:')),
                ('ubicacion_geofrafica', models.CharField(max_length=60, verbose_name='Ubicacion geografica')),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuncionesEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=60, verbose_name='Funcion:')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion de la funcion:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
            ],
            options={
                'verbose_name': 'Funcion del empleado',
                'verbose_name_plural': 'Funciones de los empleados',
            },
        ),
        migrations.CreateModel(
            name='TipoTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de tabla:')),
            ],
            options={
                'verbose_name': 'Tipo de tabla',
                'verbose_name_plural': 'Tipos de tablas',
            },
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cedula', models.CharField(max_length=60, verbose_name='Nit / Cedula:')),
                ('nombre_apellido', models.CharField(max_length=60, verbose_name='nombre y Apellidos')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo de empleado:')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de empleado',
                'verbose_name_plural': 'Tipos de empleado',
            },
        ),
        migrations.CreateModel(
            name='SemanaAnio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Semana del año:')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('fecha_inicial', models.DateTimeField(verbose_name='Fecha Inicial:')),
                ('fecha_final', models.DateTimeField(verbose_name='Fecha Final:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.color')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semanas del año',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de programacion:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.semanaanio')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesos', models.CharField(max_length=60, verbose_name='Procesos:')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripcion del proceso:')),
                ('estado', models.BooleanField(default=True)),
                ('id_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='Labores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.CharField(max_length=60, verbose_name='Labor:')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripcion de la labor:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
            },
        ),
        migrations.CreateModel(
            name='FuncionesXEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.empleados')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.funcionesempleados')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FuncionesXEmpleado',
            },
        ),
        migrations.AddField(
            model_name='funcionesempleados',
            name='id_tipo_tabla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla'),
        ),
        migrations.AddField(
            model_name='funcionesempleados',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EntradaVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_vehiculo', models.CharField(max_length=20, verbose_name='Placa del vehiculo:')),
                ('carga_entrada', models.CharField(max_length=40, verbose_name='Carga de entrada:')),
                ('carga_salida', models.CharField(max_length=40, verbose_name='Carga de la salida:')),
                ('n_poma', models.IntegerField()),
                ('cantidad_pales', models.IntegerField()),
                ('cajas_sueltas', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acceso.empleados')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='acceso.visitantes')),
            ],
            options={
                'verbose_name': 'Entrada y salida de vehiculo',
                'verbose_name_plural': 'Entrada y salida de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalidaVisitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha:')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de Entrada:')),
                ('detalle_entrada', models.CharField(max_length=200, verbose_name='Detalle de entrada:')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida:')),
                ('detalle_salida', models.CharField(max_length=200, verbose_name='Detalle de la salida:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.semanaanio')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.visitantes')),
            ],
            options={
                'verbose_name': 'Entrada y salida de visita',
                'verbose_name_plural': 'Entradas y salidas de visitas',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalidaEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha:')),
                ('hora_entrada', models.TimeField(verbose_name='Hora de entrada:')),
                ('detalle_entrada', models.CharField(max_length=200, verbose_name='Detalle de la entrada:')),
                ('hora_salida', models.TimeField(verbose_name='Hora de Salida:')),
                ('detalle_salida', models.CharField(max_length=200, verbose_name='Detalle de la Salida:')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.empleados')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.semanaanio')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entradas y salidas de empleados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=60, verbose_name='NIT:')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre:')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion:')),
                ('telefonos', models.CharField(max_length=80, verbose_name='telefonos de la empresa:')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_tipo_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.tipoempleado'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_tipo_tabla',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleProgramacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.empleados')),
                ('id_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas')),
                ('id_labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.labores')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.procesos')),
                ('id_programacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.programacion')),
                ('id_tipo_tabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de programacion',
                'verbose_name_plural': 'Detalles de programaciones',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='id_finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas'),
        ),
        migrations.AddField(
            model_name='color',
            name='id_tipo_tabla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla'),
        ),
        migrations.AddField(
            model_name='color',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acceso.fincas'),
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_tipo_tabla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acceso.tipotabla'),
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
