# Generated by Django 3.1 on 2020-08-31 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoTabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=80, verbose_name='Tipo de tabla:')),
            ],
            options={
                'verbose_name': 'Tipo de tabla',
                'verbose_name_plural': 'Tipos de tablas',
            },
        ),
        migrations.CreateModel(
            name='Fincas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre:')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion:')),
                ('ubicacionGeofrafica', models.CharField(max_length=60, verbose_name='Ubicacion geografica')),
                ('Responsable', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nit', models.CharField(max_length=60, verbose_name='NIT:')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre:')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion:')),
                ('Telefonos', models.CharField(max_length=80, verbose_name='Telefonos de la empresa:')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
