# Generated by Django 3.1 on 2020-08-31 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo', models.CharField(max_length=40, verbose_name='Cargo:')),
                ('Descripcion', models.CharField(max_length=300, verbose_name='Descripcion del cargo:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=20, verbose_name='Color:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=50, verbose_name='Cedula:')),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre del empleado:')),
                ('Apellido', models.CharField(max_length=20, verbose_name='Apellido del empledado:')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion del empleado:')),
                ('Telefonos', models.CharField(max_length=80, verbose_name='Telefonos del empleado:')),
                ('Mail', models.CharField(max_length=30, verbose_name='Correo Electronico:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.cargos')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='FuncionesEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funcion', models.CharField(max_length=60, verbose_name='Funcion:')),
                ('Descripcion', models.CharField(max_length=300, verbose_name='Descripcion de la funcion:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcion del empleado',
                'verbose_name_plural': 'Funciones de los empleados',
            },
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitCedula', models.CharField(max_length=60, verbose_name='Nit / Cedula:')),
                ('nombreApellido', models.CharField(max_length=60, verbose_name='Nombre y Apellidos')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=20, verbose_name='Tipo de empleado:')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='Descripcion:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de empleado',
                'verbose_name_plural': 'Tipos de empleado',
            },
        ),
        migrations.CreateModel(
            name='SemanaAnio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semana', models.IntegerField(verbose_name='Semana del año:')),
                ('Year', models.IntegerField(verbose_name='Año')),
                ('fechaInicial', models.DateTimeField(verbose_name='Fecha Inicial:')),
                ('fechaFinal', models.DateTimeField(verbose_name='Fecha Final:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.color')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semanas del año',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha de programacion:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.semanaanio')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Procesos', models.CharField(max_length=60, verbose_name='Procesos:')),
                ('Descripcion', models.CharField(max_length=60, verbose_name='Descripcion del proceso:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='Labores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labor', models.CharField(max_length=60, verbose_name='Labor:')),
                ('Descripcion', models.CharField(max_length=60, verbose_name='Descripcion de la labor:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idTipoTabla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labores',
            },
        ),
        migrations.CreateModel(
            name='FuncionesXEmpleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.empleados')),
                ('idFuncion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.funcionesempleados')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FuncionesXEmpleado',
            },
        ),
        migrations.CreateModel(
            name='EntradaVehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaVehiculo', models.CharField(max_length=20, verbose_name='Placa del vehiculo:')),
                ('cargaEntrada', models.CharField(max_length=40, verbose_name='Carga de entrada:')),
                ('cargaSalida', models.CharField(max_length=40, verbose_name='Carga de la salida:')),
                ('NPoma', models.IntegerField()),
                ('cantidadPales', models.IntegerField()),
                ('cajasSueltas', models.IntegerField()),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idEmpleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acceso.empleados')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('idVisitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acceso.visitantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada y salida de vehiculo',
                'verbose_name_plural': 'Entrada y salida de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalidaVisitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha:')),
                ('horaEntrada', models.TimeField(verbose_name='Hora de Entrada:')),
                ('detalleEntrada', models.CharField(max_length=200, verbose_name='Detalle de entrada:')),
                ('horaSalida', models.TimeField(verbose_name='Hora de salida:')),
                ('detalleSalida', models.CharField(max_length=200, verbose_name='Detalle de la salida:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.semanaanio')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('idVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.visitantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada y salida de visita',
                'verbose_name_plural': 'Entradas y salidas de visitas',
            },
        ),
        migrations.CreateModel(
            name='EntradaSalidaEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha:')),
                ('horaEntrada', models.TimeField(verbose_name='Hora de entrada:')),
                ('detalleEntrada', models.CharField(max_length=200, verbose_name='Detalle de la entrada:')),
                ('horaSalida', models.TimeField(verbose_name='Hora de Salida:')),
                ('detalleSalida', models.CharField(max_length=200, verbose_name='Detalle de la Salida:')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.empleados')),
                ('idSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.semanaanio')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entradas y salidas de empleados',
            },
        ),
        migrations.AddField(
            model_name='empleados',
            name='idTipoEmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.tipoempleado'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='idTipoTabla',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetalleProgramacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.fincas')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.empleados')),
                ('idLabor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.labores')),
                ('idProceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.procesos')),
                ('idProgramacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.programacion')),
                ('idTipoTabla', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='acceso.tipotabla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle de programacion',
                'verbose_name_plural': 'Detalles de programaciones',
            },
        ),
    ]
